title: Preetika Kaur
description: "University of Wyoming"
logo: /images/headshot.jpg
theme: jekyll-theme-Minimal

# Layout


show_excerpts: TRUE        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: True             # use a dark header

navigation:
-{file: "Publications.md", title: "Publications"}
